import React from 'react';
import { Vessel } from '../types/maritime';

interface VesselPopupProps {
  vessel: Vessel;
}

// NOTE: Since pointLabel in react-globe.gl requires an HTML string, 
// we provide a static function to generate the HTML.
export const getVesselHTML = (v: any) => {
  const signal = v.signal?.status || 'NEUTRAL';
  const cargo = v.cargo || {};
  return `
  <div class="glass-panel intelligence-popup transition-all duration-300 transform scale-100 min-w-[280px]">
    <div class="popup-header bg-surface-2/50 p-3 flex justify-between items-start border-b border-white/10">
      <div class="flex flex-col">
        <span class="type-h2 text-text-1 font-bold tracking-tight">${v.name || 'Unknown Vessel'}</span>
        <span class="type-data-xs text-text-4 font-mono">${v.mmsi || 'N/A'} | ${v.operator || 'Independent'}</span>
      </div>
      <span class="signal-badge ${signal === 'BULLISH' ? 'signal-bull' : signal === 'BEARISH' ? 'signal-bear' : 'signal-neutral'} shadow-lg py-1 px-2 rounded font-bold text-[10px]">
        ${signal}
      </span>
    </div>
    <div class="popup-body p-3">
      <div class="space-y-1.5 font-mono">
        <div class="data-row flex justify-between"><span class="data-label text-text-4 text-[10px] uppercase">Class</span><span class="data-value text-accent-secondary text-[11px] font-bold">${v.type || 'Cargo'} ${v.class ? `(${v.class})` : ''}</span></div>
        <div class="data-row flex justify-between"><span class="data-label text-text-4 text-[10px] uppercase">Route</span><span class="data-value text-[11px]">${v.origin || 'N/A'} → ${v.destination || 'N/A'}</span></div>
        <div class="data-row flex justify-between pt-1 border-t border-white/5"><span class="data-label text-text-4 text-[10px] uppercase">Cargo</span><span class="data-value text-bull text-[11px] font-bold">${cargo.type || 'General'}</span></div>
        <div class="data-row flex justify-between"><span class="data-label text-text-4 text-[10px] uppercase">Manifest</span><span class="data-value text-[10px] italic text-text-2">${cargo.manifest || 'No details available'}</span></div>
        <div class="data-row flex justify-between"><span class="data-label text-text-4 text-[10px] uppercase">Quantity</span><span class="data-value text-[11px]">${cargo.quantity || 'Bulk'} ${cargo.teu ? `(${cargo.teu} TEU)` : ''}</span></div>
        <div class="data-row flex justify-between"><span class="data-label text-text-4 text-[10px] uppercase">Shipper</span><span class="data-value text-[10px]">${cargo.shipper || 'Unknown'}</span></div>
      </div>

      <div class="mt-4 pt-3 border-t border-white/10">
        <div class="flex flex-wrap gap-1 mb-2">
          ${v.tickers && Array.isArray(v.tickers) ? v.tickers.map((t: string) => `<span class="ticker-chip bg-accent-primary/10 text-accent-primary border border-accent-primary/20 px-1.5 py-0.5 rounded text-[9px] font-bold">${t}</span>`).join('') : ''}
        </div>
        <div class="type-data-xs text-text-4 leading-tight border-l-2 border-accent-primary pl-2 py-1 bg-accent-primary/5">
          <span class="text-accent-primary font-bold">ALPHA INTEL:</span> ${v.signal?.reason || 'Scanning...'}
        </div>
      </div>
      
      <div class="flex justify-between items-center mt-3 pt-2 border-t border-white/10">
        <div class="flex flex-col">
           <span class="text-[9px] text-text-5 uppercase tracking-widest font-bold">Est. Economic Impact</span>
           <span class="text-sm font-black text-bull tracking-tighter">$${(v.signal?.impact || 0).toFixed(1)}M USD</span>
        </div>
      </div>
    </div>
    <div class="h-1 w-full bg-surface-1 relative">
      <div class="absolute left-0 top-0 h-full bg-bull shadow-[0_0_8px_rgba(0,255,157,0.5)] transition-all duration-1000" style="width: ${v.progress_pct || 0}%"></div>
    </div>
  </div>
`;
};

const VesselPopup: React.FC<VesselPopupProps> = ({ vessel }) => {
  return null; // Used for type reference primarily, HTML generated by template
};

export default VesselPopup;
